#!/bin/sh

set -e

if [ ! -d "$(pwd)/node_modules" ]; then
  mkdir -p $(pwd)/node_modules
fi

if [ ! -e "$(pwd)/node_modules/programmatic" ]; then
  ln -s $(pwd) $(pwd)/node_modules/programmatic
fi

echo ""

(proof run t/*/*.t.js | tee .proof.out | proof progress) || \
  (proof errors < .proof.out) || exit 1

if [ "$TRAVIS" = "true" ]; then
  echo "generating coverage"
  t/cover

  echo "submitting coverage to coveralls.io"
  cat coverage/lcov.info | node_modules/.bin/coveralls > /dev/null

  curl 'https://www.prettyrobots.com/travisty' | sh
fi

echo ""
