#!/bin/sh

set -e

if [ "$TRAVIS" = "true" ]; then
  echo '$ sudo apt-get install bc' && echo ''
  sudo apt-get install -q -q bc 2> /dev/null > /dev/null
fi

t/sizes index.js | sed 's/^/    /'

echo ""

(proof run t/*/*.t.js | tee .proof.out | proof progress) || \
  (proof errors < .proof.out) || exit 1

if [ "$TRAVIS" = "true" ]; then
  echo "generating coverage"
  t/cover

  echo "submitting coverage to coveralls.io"
  cat coverage/lcov.info | node_modules/.bin/coveralls > /dev/null

  curl 'https://www.prettyrobots.com/travisty' | sh
fi

echo ""
